version: '2.2'
services:
  rabbit:
    image: rabbitmq:management-alpine
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment: 
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
      
  sqldb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  