version: '2.2'
services:
  rabbit:
    image: rabbitmq:management
    container_name: "rabbitmq-quartz"
    ports:
      - "15672:15672"
      - "5672:5672"
  sqldb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  